<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	<IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Pratyaksh\Core\Pratyaksh.Core.csproj" />
    <ProjectReference Include="..\..\Pratyaksh\UI\Pratyaksh.UI.csproj" />
    <ProjectReference Include="..\..\Pratyaksh\Node\Core\Pratyaksh.Node.Core.csproj" />
    <ProjectReference Include="..\..\Pratyaksh\Node\Editor\Pratyaksh.Node.Editor.csproj" />
  </ItemGroup>

</Project>
