<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Pratyaksh.Node.Editor</PackageId>
    <Description>Pratyaksh Node Library Editor.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Pratyaksh.Core.csproj" />
    <ProjectReference Include="..\..\UI\Pratyaksh.UI.csproj" />
    <ProjectReference Include="..\Core\Pratyaksh.Node.Core.csproj" />
  </ItemGroup>

</Project>
