<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\Pratyaksh.Core.csproj" />
    <ProjectReference Include="..\..\UI\Pratyaksh.UI.csproj" />
    <ProjectReference Include="..\Core\Pratyaksh.Node.Core.csproj" />
  </ItemGroup>

</Project>
