<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Pratyaksh.UI</PackageId>
    <Description>Standalone UI library component toolkit.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Pratyaksh.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.0.0" />
  </ItemGroup>

</Project>
